2021-04-29 09:03:10,176 ERROR: Exception on /explore [GET] [in /home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/routes.py", line 139, in explore
    posts = Post.query.order_by(Post_timestamp.desc()). all()
NameError: name 'Post_timestamp' is not defined
2021-04-29 09:06:43,611 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:07:20,696 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:07:24,559 ERROR: Exception on /explore [GET] [in /home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/routes.py", line 139, in explore
    posts = Post.query.order_by(Post_timestamp.desc()).all()
NameError: name 'Post_timestamp' is not defined
2021-04-29 09:07:54,817 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:20:12,114 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:40:55,102 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-04-29 09:42:41,060 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-12-07 06:11:55,579 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-12-07 06:17:04,730 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-12-07 06:19:40,381 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:41]
2021-12-07 06:31:18,199 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:42]
2021-12-07 06:41:46,096 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:42]
2021-12-07 06:52:05,489 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:42]
2021-12-07 06:52:16,243 ERROR: Exception on /login [GET] [in /home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/routes.py", line 49, in login
    return render_template('login.html', title='Lab Sign In', form=form)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/templates/base.html", line 33, in top-level template code
    {% block content %} {% endblock %}
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/app/templates/login.html", line 27, in block "content"
    <a href=" {{ url_for('reset_password_request') }}">Click to Reset</a>
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/cenright/Documents/coding/GITproject/flask/bagl/lib64/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2021-12-07 07:09:47,930 INFO: BAGL startup [in /home/cenright/Documents/coding/GITproject/flask/bagl/app/__init__.py:42]
